# Generated by Django 5.2.6 on 2025-09-26 08:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="病例的标题或名称",
                        max_length=200,
                        verbose_name="病例名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="详细的病例描述和背景信息", verbose_name="病例描述"
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        help_text="患者的主要症状和表现", verbose_name="症状表现"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        help_text="各项检查的详细结果", 
                        verbose_name="诊断结果",
                        default="待补充"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="相关的检查图片或眼底照片",
                        null=True,
                        upload_to="case_images/",
                        verbose_name="病例图像",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        max_length=10,
                        choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')],
                        default='medium',
                        help_text="病例难度等级",
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        max_length=20,
                        choices=[('clinical', '临床病例'), ('surgery', '手术病例'), ('emergency', '急诊病例')],
                        default='clinical',
                        help_text="病例类型分类",
                        verbose_name="病例类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否在教学中使用此病例",
                        verbose_name="是否启用",
                    ),
                ),
            ],
            options={
                "verbose_name": "眼科病例",
                "verbose_name_plural": "眼科病例",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="题目的问题内容", verbose_name="题干"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "单选题"),
                            ("multiple", "多选题"),
                            ("judge", "判断题"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "options",
                    models.TextField(
                        help_text='题目选项，JSON格式存储，如：["A选项", "B选项", "C选项", "D选项"]',
                        verbose_name="选项",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="正确答案，单选填A/B/C/D，多选填AB/AC等，判断题填T/F",
                        max_length=50,
                        verbose_name="正确答案",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="题目答案的详细解析",
                        verbose_name="答案解析",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        default=1,
                        help_text="1-5级，1最简单，5最难",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="此题目关联的病例",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="cases.case",
                        verbose_name="关联病例",
                    ),
                ),
            ],
            options={
                "verbose_name": "练习题目",
                "verbose_name_plural": "练习题目",
                "ordering": ["case", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="考试标题"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="考试的详细说明和注意事项",
                        verbose_name="考试说明",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="考试开始的具体时间", verbose_name="开始时间"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        help_text="考试持续时间，单位：分钟", verbose_name="考试时长"
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2, default=100.0, max_digits=5, verbose_name="总分"
                    ),
                ),
                (
                    "pass_score",
                    models.DecimalField(
                        decimal_places=2, default=60.0, max_digits=5, verbose_name="及格分"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("in_progress", "进行中"),
                            ("finished", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="考试状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "exercises",
                    models.ManyToManyField(
                        help_text="本次考试包含的题目",
                        to="cases.exercise",
                        verbose_name="考试题目",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="参与此次考试的学生，如果为空则所有学生都可参与",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="参与学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试",
                "verbose_name_plural": "考试",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ExamRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("practice", "练习模式"),
                            ("exam", "正式考试"),
                            ("mock", "模拟考试"),
                        ],
                        default="exam",
                        max_length=20,
                        verbose_name="考试类型",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="考试得分，满分100分",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="得分",
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="题目总数"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="正确答案数"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        default=0,
                        help_text="考试用时，单位：分钟",
                        verbose_name="用时（分钟）",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="cases.exam",
                        verbose_name="关联考试",
                    ),
                ),
                (
                    "exercises",
                    models.ManyToManyField(
                        help_text="本次考试包含的题目",
                        to="cases.exercise",
                        verbose_name="关联练习题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试记录",
                "verbose_name_plural": "考试记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="学习进度百分比",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="进度百分比",
                    ),
                ),
                (
                    "total_study_time",
                    models.IntegerField(
                        default=0,
                        help_text="总学习时长，单位：分钟",
                        verbose_name="总学习时长",
                    ),
                ),
                (
                    "last_study_date",
                    models.DateTimeField(auto_now=True, verbose_name="最后学习时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_cases",
                    models.ManyToManyField(
                        blank=True,
                        help_text="用户已学习完成的病例",
                        to="cases.case",
                        verbose_name="完成的病例",
                    ),
                ),
                (
                    "completed_exercises",
                    models.ManyToManyField(
                        blank=True,
                        help_text="用户已完成的练习题目",
                        to="cases.exercise",
                        verbose_name="完成的练习",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户进度",
                "verbose_name_plural": "用户进度",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.CharField(max_length=50, verbose_name="用户答案"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="是否正确"),
                ),
                (
                    "answer_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="答题时间"),
                ),
                (
                    "exam_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="cases.examrecord",
                        verbose_name="考试记录",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="cases.exercise",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户答题记录",
                "verbose_name_plural": "用户答题记录",
                "unique_together": {("user", "exercise", "exam_record")},
            },
        ),
    ]