# Generated by Django 5.2.6 on 2025-09-26 10:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_updated_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="考试得分，满分100分",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="得分",
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(default=0, verbose_name="题目总数"),
                ),
                (
                    "correct_answers",
                    models.IntegerField(default=0, verbose_name="正确答案数"),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        default=0,
                        help_text="考试用时，单位：分钟",
                        verbose_name="考试用时",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="完成时间"),
                ),
                (
                    "answers",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式存储答题详情",
                        verbose_name="答题记录",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="本次考试包含的题目",
                        to="cases.exercise",
                        verbose_name="考试题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "模拟考试结果",
                "verbose_name_plural": "模拟考试结果",
                "ordering": ["-created_at"],
            },
        ),
    ]
