# Generated by Django 5.2.6 on 2025-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_examresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="examrecord",
            name="is_passed",
            field=models.BooleanField(
                default=False, help_text="是否达到及格分数线", verbose_name="是否通过"
            ),
        ),
    ]
