# Generated by Django 5.2.6 on 2025-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_clinicalcase_diagnosisoption_examinationoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationoption',
            name='fundus_reminder_text',
            field=models.CharField(default='请移步旁边进行观察', max_length=200, verbose_name='眼底检查提示文字'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='is_fundus_exam',
            field=models.BooleanField(default=False, verbose_name='是否眼底检查'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='is_multiple_choice',
            field=models.BooleanField(default=False, verbose_name='是否允许多选'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='is_required',
            field=models.BooleanField(default=False, help_text='必选检查项必须被选择才能进入下一步', verbose_name='是否必选检查'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='selection_group',
            field=models.CharField(blank=True, help_text='同组内的检查项可以一起选择', max_length=50, verbose_name='选择组'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='diagnosis_reasoning_text',
            field=models.TextField(blank=True, help_text='学生的诊断思路和推理过程', verbose_name='诊断推理过程'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='examination_images_viewed',
            field=models.JSONField(default=list, verbose_name='已查看的检查图像'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='examination_selection_valid',
            field=models.BooleanField(default=False, verbose_name='检查选择是否有效'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='reasoning_score',
            field=models.FloatField(default=0.0, verbose_name='推理过程得分'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='required_examinations_completed',
            field=models.BooleanField(default=False, verbose_name='必选检查是否完成'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='step_completion_status',
            field=models.JSONField(default=dict, help_text='记录每个步骤的完成情况：{step_name: {completed: bool, score: float, completion_time: datetime}}', verbose_name='步骤完成状态'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='step_start_times',
            field=models.JSONField(default=dict, verbose_name='各步骤开始时间'),
        ),
        migrations.AlterField(
            model_name='examinationoption',
            name='examination_type',
            field=models.CharField(choices=[('basic', '基础检查'), ('imaging', '影像检查'), ('laboratory', '实验室检查'), ('special', '特殊检查'), ('fundus', '眼底检查')], max_length=50, verbose_name='检查类型'),
        ),
        migrations.AlterField(
            model_name='studentclinicalsession',
            name='session_status',
            field=models.CharField(choices=[('case_presentation', '病例呈现'), ('examination_selection', '检查选择'), ('examination_results', '检查结果'), ('diagnosis_reasoning', '诊断推理'), ('treatment_selection', '治疗选择'), ('learning_feedback', '学习反馈'), ('completed', '已完成')], default='case_presentation', max_length=30, verbose_name='当前阶段'),
        ),
    ]
