# Generated by Django 5.2.6 on 2025-10-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_examinationoption_fundus_reminder_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationoption',
            name='left_eye_pressure',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='正常范围：10-21', max_digits=4, null=True, verbose_name='左眼眼压 (mmHg)'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='left_eye_vision',
            field=models.CharField(blank=True, help_text='如：0.8, 1.0', max_length=10, verbose_name='左眼视力'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='right_eye_pressure',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='正常范围：10-21', max_digits=4, null=True, verbose_name='右眼眼压 (mmHg)'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='right_eye_vision',
            field=models.CharField(blank=True, help_text='如：0.8, 1.0', max_length=10, verbose_name='右眼视力'),
        ),
    ]
