# Generated by Django 5.2.6 on 2025-10-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_examinationoption_left_eye_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationoption',
            name='left_eye_image',
            field=models.ImageField(blank=True, help_text='OCT或眼底照相的左眼图片', null=True, upload_to='examination_images/', verbose_name='左眼检查图片'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='right_eye_image',
            field=models.ImageField(blank=True, help_text='OCT或眼底照相的右眼图片', null=True, upload_to='examination_images/', verbose_name='右眼检查图片'),
        ),
    ]
