# Generated by Django 5.2.6 on 2025-10-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_examinationoption_left_eye_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclinicalsession',
            name='session_data',
            field=models.JSONField(default=dict, help_text='保存检查顺序、当前进度等临时数据', verbose_name='会话数据'),
        ),
    ]
