# Generated by Django 5.2.6 on 2025-10-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_studentclinicalsession_session_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationoption',
            name='additional_images',
            field=models.JSONField(blank=True, help_text='除左右眼主要图像外的其他相关图像', null=True, verbose_name='附加图像'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='image_annotations',
            field=models.JSONField(blank=True, help_text='图像上的标注信息，包含坐标和说明文字', null=True, verbose_name='图像标注'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='image_display_mode',
            field=models.CharField(choices=[('single', '单张显示'), ('comparison', '对比显示'), ('sequence', '序列显示'), ('overlay', '叠加显示')], default='single', max_length=20, verbose_name='图像显示模式'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='image_findings',
            field=models.TextField(blank=True, help_text='图像中可以观察到的病理改变', verbose_name='图像所见'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='is_oct_exam',
            field=models.BooleanField(default=False, verbose_name='是否OCT检查'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='oct_measurement_data',
            field=models.JSONField(blank=True, help_text='OCT的各项测量数据，如RNFL厚度等', null=True, verbose_name='OCT测量数据'),
        ),
        migrations.AddField(
            model_name='examinationoption',
            name='oct_report_text',
            field=models.TextField(blank=True, help_text='OCT检查的详细文字报告', verbose_name='OCT报告文字描述'),
        ),
    ]
