# Generated by Django 5.2.6 on 2025-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_examinationoption_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclinicalsession',
            name='selected_diagnoses',
            field=models.JSONField(default=list, help_text='支持鉴别诊断的多选功能', verbose_name='选中的多个诊断ID'),
        ),
    ]
