# Generated by Django 5.2.6 on 2025-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_studentclinicalsession_selected_diagnoses'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisoption',
            name='hint_level_1',
            field=models.TextField(blank=True, help_text='第一次错误时给出的轻度提示', verbose_name='轻度提示'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='hint_level_2',
            field=models.TextField(blank=True, help_text='第二次错误时给出的中度提示', verbose_name='中度提示'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='hint_level_3',
            field=models.TextField(blank=True, help_text='第三次错误时给出的强提示', verbose_name='强提示'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='diagnosis_attempt_count',
            field=models.IntegerField(default=0, help_text='记录学生诊断尝试的次数，用于循序渐进指导', verbose_name='诊断尝试次数'),
        ),
        migrations.AddField(
            model_name='studentclinicalsession',
            name='diagnosis_guidance_level',
            field=models.IntegerField(default=0, help_text='0=无提示，1=轻度提示，2=中度提示，3=强提示', verbose_name='指导级别'),
        ),
    ]
