# Generated by Django 5.2.6 on 2025-10-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_add_diagnosis_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisoption',
            name='diagnostic_difficulty',
            field=models.IntegerField(choices=[(1, '容易识别'), (2, '中等难度'), (3, '困难识别')], default=2, verbose_name='识别难度'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='interference_level',
            field=models.IntegerField(choices=[(1, '低干扰'), (2, '中干扰'), (3, '高干扰')], default=2, help_text='作为错误选项时的干扰强度', verbose_name='干扰程度'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='推荐但非必需的诊断选项', verbose_name='是否推荐诊断'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='is_required',
            field=models.BooleanField(default=False, help_text='必选诊断必须被选中才算完全正确', verbose_name='是否必选诊断'),
        ),
    ]
