# Generated by Django 5.2.6 on 2025-11-18 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_optimize_diagnosis_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('student_question', '学生提问'), ('patient_response', '病人回答'), ('system_hint', '系统提示')], max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('stage', models.CharField(choices=[('history', '病史采集'), ('examination', '体格检查'), ('diagnosis', '诊断推理'), ('treatment', '治疗选择'), ('feedback', '学习反馈')], max_length=20, verbose_name='所属阶段')),
                ('matched_keywords', models.JSONField(blank=True, default=list, help_text='触发此回答的关键词列表', verbose_name='匹配的关键词')),
                ('confidence_score', models.FloatField(default=0.0, help_text='关键词匹配的置信度分数', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='匹配置信度')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('is_important', models.BooleanField(default=False, help_text='标记是否为诊断关键信息', verbose_name='重要信息')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='cases.studentclinicalsession', verbose_name='学习会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PatientResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list, help_text='触发此回答的关键词，支持同义词', verbose_name='关键词列表')),
                ('response_text', models.TextField(verbose_name='病人回答内容')),
                ('priority', models.IntegerField(default=0, help_text='数值越大优先级越高，同时匹配多个模板时使用', verbose_name='优先级')),
                ('information_category', models.CharField(choices=[('chief_complaint', '主诉相关'), ('present_illness', '现病史'), ('past_history', '既往史'), ('family_history', '家族史'), ('personal_history', '个人史'), ('physical_exam', '体格检查'), ('general', '一般信息')], default='present_illness', max_length=50, verbose_name='信息类别')),
                ('diagnostic_importance', models.CharField(choices=[('critical', '关键信息'), ('important', '重要信息'), ('supportive', '支持性信息'), ('irrelevant', '无关信息')], default='supportive', max_length=20, verbose_name='诊断重要性')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('max_triggers', models.IntegerField(default=0, help_text='0表示无限制，>0表示最多触发次数', verbose_name='最大触发次数')),
                ('trigger_count', models.IntegerField(default=0, verbose_name='已触发次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_templates', to='cases.clinicalcase', verbose_name='临床病例')),
            ],
            options={
                'verbose_name': '病人回答模板',
                'verbose_name_plural': '病人回答模板',
                'ordering': ['-priority', 'information_category'],
            },
        ),
    ]
