# Generated by Django 5.2.6 on 2025-12-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_chatmessage_patientresponsetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalcase',
            name='conjunctiva_exam',
            field=models.TextField(blank=True, help_text='结膜充血、水肿等', verbose_name='结膜检查'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='cornea_exam',
            field=models.TextField(blank=True, help_text='角膜透明度、表面等', verbose_name='角膜检查'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='external_eye_exam',
            field=models.TextField(blank=True, help_text='眼睑、眼球位置、运动等', verbose_name='眼外观检查'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='intraocular_pressure',
            field=models.TextField(blank=True, help_text='如：右眼15mmHg，左眼16mmHg', verbose_name='眼压'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='pupil_exam',
            field=models.TextField(blank=True, help_text='瞳孔大小、形状、对光反应等', verbose_name='瞳孔检查'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='visual_acuity',
            field=models.TextField(blank=True, help_text='如：右眼0.3，左眼0.5', verbose_name='视力'),
        ),
    ]
