# Generated by Django 5.2.6 on 2025-12-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_clinicalcase_conjunctiva_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisoption',
            name='correct_rationale',
            field=models.TextField(blank=True, help_text='用于与学生输入的诊断依据进行文本匹配的标准答案', verbose_name='标准诊断依据'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='diagnosis_description',
            field=models.TextField(blank=True, help_text='诊断的详细描述', verbose_name='诊断描述'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', '容易'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度级别'),
        ),
        migrations.AddField(
            model_name='diagnosisoption',
            name='key_points',
            field=models.TextField(blank=True, help_text='用逗号或分号分隔的关键词列表，用于评估学生诊断依据是否涵盖重要知识点', verbose_name='关键点'),
        ),
    ]
