# Generated by Django 5.2.6 on 2025-12-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_diagnosisoption_correct_rationale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentoption',
            name='correct_rationale',
            field=models.TextField(blank=True, default='', verbose_name='正确的治疗依据'),
        ),
        migrations.AddField(
            model_name='treatmentoption',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度等级'),
        ),
        migrations.AddField(
            model_name='treatmentoption',
            name='key_points',
            field=models.TextField(blank=True, default='', verbose_name='关键要点（每行一个）'),
        ),
    ]
